### ISSUE TITLE
Porting RACR to Python

### ISSUE THREAD

**Issue by volcacius** [christoff-buerger/racr#90]
Hello,

I'm interested in exploring the feasibility of porting RACR to Python, to be leveraged as a library. I don't really have much experience with Scheme-like languages so please bear with me if I say anything stupid. I couldn't find any R6RS Scheme implementation running on top of Python, but a couple of things that seem might make sense are to try to port it to [Hissp](https://github.com/gilch/hissp) or [Pycket](https://github.com/pycket/pycket). For my use case performance is really not a problem, so for Pycket I'd just run the RPython code on top of CPython. 
I was wondering if you have experience with this/suggestions to share/anything really. 

Thanks

Alessandro

**Comment by christoff-buerger** [comment]
Dear Alessandro,

A _RACR_ <-> _Python_ integration -- with arbitrary callback directions -- already has been implemented by a former colleague of me at TU Dresden a few years ago; it was based on _Racket_ as Scheme VM. Thus, I know it is doable with reasonable effort.

The code of that implementation is MIT licensed, but unfortunately mingled in a project repository with further project-specific code that you don't need and whose license is not clear. I would anyway recommend to start a new implementation based on another scheme VM since Racket's performance is not recommendable for _R6RS_ with _mutable lists_ (i.e., real graph data) as used by _RACR_; fortunately, since then a very good Scheme VM -- the former commercial [_Chez Scheme_](https://github.com/cisco/ChezScheme) -- has been released under Apache-2.0 license; that one is a real performance blast, often faster than equivalent _C_-code programs.

Please note, that one of the really neat things of _RACR_ is the **immense** performance boost possible due to incremental evaluation; particularly if you have some kind of interactive runtime-models with analyses and runtime updates. Considering the availability of the very performant _Chez Scheme_, I therefore would recommend to consider performance right from the start.

Regarding the implementation effort, I think it is low. What you would have to do is to map all the _RACR_ interface functions summarised in the [reference manual](https://github.com/christoff-buerger/racr/blob/master/racr/documentation/api-index.md) to respective _Python_ functions and define an AST-node wrapper in _Python_ so you can hold AST-nodes in your _Python_ program (since most functions use an abstract syntax tree node argument to denote the AST-part they are working on). This is very similar to the C#/.NET interface _RACR_ already provides (if you can read German the [manual](https://github.com/christoff-buerger/racr/blob/master/racr-net/documentation/title.md) will give you a very good idea what has to be done).

The important questions you have to make up your mind are:

  1. How do you like to use _RACR_; is it (1) called from within _Python_ or do you want to call _Python_ code from within _Scheme_ programs -- thus, what is your main programming language/host language, _Python_ or _Scheme_? Given your post, I already assumed (1) in my above comments and the following.
  2. Do you need callbacks (i.e., _Python_ code calls _RACR_ attributes whose definition in turn calls some _Python_ function. The trick with callbacks is...
  3. How to take care of the _Scheme_ garbage collector. A foreign function interface (FFI) must take care not to accidentally collect AST nodes that will be used later on. Typically, you do not want any AST nodes constructed from within Python to be collected by the _Scheme_ system nor let _Python_ code free nodes that are exposed by callbacks.

Regarding points (2) and (3), there are some good existing FFI implementations for _R6RS Scheme_; particularly (1) [r6rs-pfffi](https://github.com/ktakashi/r6rs-pffi) with _C_ bindings for different _Scheme_ systems and (2) [Darkart](https://github.com/guenchi/Darkart) for _Chez Scheme_. (1) another colleague already used for a _C_ binding of _RACR_ in an industrial project for automatic micro-fluid chip design (lab on chip), where given a desired mixing/chemical result an optimal chip-layout has to be derived via analyses (thus, high benefit of incremental evaluation in a design process with semi-automatic redesign/rewrites of a current design derived by said analyses). Note, that (2) _is_ used to provide _Scheme_ bindings for lot of the SciPy _Python_ packages like Matplotlib, NumPy etc (just check the following [project list](https://github.com/topics/chez-scheme)); this means, the usage of Scheme as host language is feasible if you like to work in the [SciPy](https://www.scipy.org) ecosystem.

To summary I would recommend to
  1. use _Chez Scheme_ as host system to run _RACR_,
  2. develop a _C_ binding for _RACR's_ API functions such that (1) can be used from within _C_ code and
  3. develop a _Python_ binding to (2), such that altogether you have a _Python_-API to the _RACR_ hosted on _Chez Scheme_.

Note, that _Chez Scheme_ has a very good and particularly performant _C_ FFI.
